spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          max-attempts: 3
  application:
    name: notification-service
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: "digipay"
    password: "digipay"
    url: "jdbc:postgresql://localhost:5432/digipay"
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  okhttp:
    enabled: true
server:
  port: 8084

notification-service:
  exchange:
    name: "notification-exchange"
  queue:
    name: "notification-queue"
  routing:
    key: "notification"