spring:
  application:
    name: auth-service
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: "digipay"
    password: "digipay"
    url: "jdbc:postgresql://localhost:5432/digipay"
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  okhttp:
    enabled: true
server:
  port: 8082